GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name" : "testisyöte",
    "number" : 112
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name" : "testisyöte" 
}

###

GET https://FS2018puhelin.now.sh/api/persons

###

GET https://FS2018puhelin.now.sh/info

###

DELETE https://FS2018puhelin.now.sh/api/persons/2

###

POST https://FS2018puhelin.now.sh/api/persons
content-type: application/json

{
    "name" : "testisyöte",
    "number" : 112
}